name: C/C++ CI

on:
  push:
    branches: [ main , farkas-martin ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    - name: make
      run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
    #We disable these options while implementation is not available
